sample_vrg_files := $(wildcard sample/*.vrg)
sample_png_files := $(patsubst %.vrg,%.png,$(sample_vrg_files))

xpro := perl xprolog/xpro.pl
xclp := perl -Ilib script/xclips.pl -I knowledge -c
vrg_run := perl -Ilib script/vrg-run.pl

xpro_files := $(wildcard xprolog/*.xpro)
pro_files  := $(patsubst %.xpro,%.pro, $(xpro_files))

clp_files  := $(patsubst %,knowledge/%,vectorize.clp vector-eval.clp \
	anti-vectorize.clp goal-match.clp)

vpath %.grammar grammar
vpath %.pl script

all: lib/XClips/Compiler/Base.pm

lib/XClips/Compiler/Base.pm: xclips.grammar
	mkdir -p lib/XClips/Compiler
	perl -s -MParse::RecDescent - -RD_HINT $< XClips::Compiler::Base
	mv Base.pm $@

%.clp: %.xclp xclips.pl lib/XClips/Compiler.pm lib/XClips/Compiler/Base.pm vrg-sugar.xclp
	$(xclp) $<

test: all
	prove -Ilib t/*.t

clean: clean
	rm lib/XClips/Compiler/Base.pm
	clips-cover -d

